halflife.wad
gfx/env/arcnup.tga
gfx/env/arcndn.tga
gfx/env/arcnlf.tga
gfx/env/arcnrt.tga
gfx/env/arcnft.tga
gfx/env/arcnbk.tga
models/mil_crategibs.mdl
sprites/laserbeam.spr
sound/ambience/arabmusic.wav
sound/ambience/car1.wav
sound/ambience/car2.wav
sound/ambience/alienwind1.wav
models/snowman.mdl
sprites/glow01.spr
overviews/de_dust2_winter16.bmp
overviews/de_dust2_winter16.txt
