halflife.wad
cstrike.wad
gfx/env/arcnup.tga
gfx/env/arcndn.tga
gfx/env/arcnlf.tga
gfx/env/arcnrt.tga
gfx/env/arcnft.tga
gfx/env/arcnbk.tga
sprites/flare1.spr
sound/ambience/cricket.wav
sprites/laserbeam.spr
models/snowman.mdl
sound/ambience2m/breather.wav
sound/ambience2m/computalk1.wav
sound/ambience2m/deadsignal2.wav
sound/ambience2m/wind1.wav
overviews/de_nuke_winter16.bmp
overviews/de_nuke_winter16.txt
